# basic options
title: Mathwworks
author: @jair2018
email: jai.ramanathan1999@gmail.com
description: Mathwworks
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
